### ISSUE TITLE
"There is a new version of LightPerms available!" while on latest version

### ISSUE THREAD

**Issue by nobodywasishere** [JEFF-Media-GbR/Spigot-LightPerms#1]
Does [this line](https://github.com/JEFF-Media-GbR/Spigot-LightPerms/blob/5b1ad3fbe35b4b85a31a1869053f76bd7d72c2d8/src/main/resources/plugin.yml#L3) need to be changed tor reflect the most recent version of 1.1.0?

**Comment by mfnalex** [comment]
yes, will be fixed

**Comment by nobodywasishere** [comment]
Thank you! And thank you for your work on all the various plugins you've made.
