### ISSUE TITLE
[Feature] World ranks and permissions

### ISSUE THREAD

**Issue by Lennord** [JEFF-Media-GbR/Spigot-LightPerms#3]
Hello, would it be possible to do ranks and permissions by worlds?

**Comment by mfnalex** [comment]
Hi, LightPerms is designed to be extremely easy to use. I basically made it for people who kept asking "why does AngelChest only work for OPs?"

Sooo, no sorry I won't add per world permissions. Maybe at point in the future.

When you need stuff like that, I'd suggest you to switch to LuckPerms instead: https://luckperms.net It even has a web-based GUI to edit permissions :)
